name = "ApproximateComputations"
uuid = "a8152800-f27e-11e8-23cf-313a6a686b00"
authors = ["Nicholas Timmons <ngtimmons@gmail.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
